---
abstract: 'The CondVar monad.'
author:
  - 'hiratara <hiratara {at} cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::More: '0.94'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Monad-CondVar
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  AnyEvent: '0'
  Data::Monad: '0.05'
  parent: '0'
  perl: v5.12.0
resources:
  bugtracker: https://github.com/hiratara/p5-Data-Monad-CondVar/issues
  homepage: https://github.com/hiratara/p5-Data-Monad-CondVar
  repository: https://github.com/hiratara/p5-Data-Monad-CondVar.git
version: '0.06'
x_contributors:
  - 'Masahiro Honma <hira.tara@gmail.com>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Yasutaka ATARASHI <yakex@cpan.org>'
  - 'hiratara <hiratara@cpan.org>'
