---
abstract: 'The CondVar monad.'
author:
  - 'hiratara <hiratara {at} cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.94
configure_requires:
  Module::Build::Tiny: 0.026
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Monad-CondVar
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  AnyEvent: 0
  Data::Monad: 0.05
  parent: 0
  perl: v5.12.0
resources:
  bugtracker: https://github.com/hiratara/p5-Data-Monad-CondVar/issues
  homepage: https://github.com/hiratara/p5-Data-Monad-CondVar
  repository: https://github.com/hiratara/p5-Data-Monad-CondVar.git
version: 0.05
